[context.deploy-preview.environment]
  TAG_MGR_ID = "GTM-K9PT3JN"
  G_4_TAG = "G-DS1W77B6LN"
  G_UNIVERSAL = "UA-204995419-2"
  SITEMAP_URL = "https://deploy-preview-defenseunicorns.netlify.app"

[context.branch-deploy]
  GATSBY_GH_TOKEN = ''